ARG FEDORA_VERSION=44
FROM quay.io/fedora/fedora-bootc:${FEDORA_VERSION} as final
# Cópia da lista de pacotes e de configurações e atribui diretório de trabalho
RUN mkdir /tmp/workdir
WORKDIR /tmp/workdir
COPY /packages/* /configs/* /scripts/* ./
# Módulos, firmware, drivers de Userspace, ,módulos e zram
RUN dnf upgrade -y --refresh && \
    grep -v '^#' ./rpms-drivers.list | tr '\n' ' ' | xargs dnf install -y --setopt=install_weak_deps=False && \
    mv -v ./0-nouveau-args.toml /usr/lib/bootc/kargs.d/0-nouveau-args.toml && \
    mv -v ./zram-generator.conf /etc/systemd/
# Ambiente gráfico - gnome-shell e mutter
RUN grep -v '^#' ./rpms-desktop.list | tr '\n' ' ' | xargs dnf install -y --setopt=install_weak_deps=False && \
    BOOTC_PLUGIN=$(curl -s https://api.github.com/repos/ramonmsilvabr/gnome-software-plugin-bootc/releases/latest | grep "browser_download_url.*\.rpm" | cut -d '"' -f 4 | head -n 1) && \
    dnf5 install -y --nogpgcheck "$BOOTC_PLUGIN" && \
    rm -f /usr/lib64/gnome-software/plugins-*/libgs_plugin_dnf5.so \
        /usr/lib64/gnome-software/plugins-*/libgs_plugin_packagekit.so \
        /usr/lib64/gnome-software/plugins-*/libgs_plugin_dkms.so
# Pacotes essenciais
RUN grep -v '^#' ./rpms-essenciais.list | tr '\n' ' ' | xargs dnf install -y --setopt=install_weak_deps=False && \
    mkdir -p /etc/plymouth && \
    mv -v ./plymouthd.conf /etc/plymouth/plymouthd.conf
WORKDIR /
RUN chmod +x /tmp/workdir/initramfs-regen.sh && \
    bash -c /tmp/workdir/initramfs-regen.sh
# Fase de Limpeza
RUN systemctl mask systemd-remount-fs.service && \
    rm -rvf /tmp/workdir && \
    dnf clean all && \
    rm -rfv /var/cache/* \
        /var/lib/* \
        /var/log/* \
        /var/tmp/*
# Ajustar container 
RUN bootc container lint