ARG FEDORA_VERSION=44
FROM quay.io/fedora/fedora-bootc:${FEDORA_VERSION} as final
# Cópia da lista de pacotes e de configurações e atribui diretório de trabalho
RUN mkdir /tmp/workdir
WORKDIR /tmp/workdir
COPY /packages/* /configs/* /scripts/* ./
# Módulos, firmware, drivers de Userspace, ,módulos e zram
RUN dnf install -y 'dnf5-command(config-manager)' && \
    dnf upgrade -y --refresh && \
    mv -v ./0-nouveau-args.toml /usr/lib/bootc/kargs.d/0-nouveau-args.toml && \
    grep -v '^#' ./rpms-drivers.list | tr '\n' ' ' | xargs dnf install -y --setopt=install_weak_deps=False && \
    mkdir -p /usr/lib/systemd/zram-generator.conf.d /usr/lib/systemd/oomd.conf.d && \
    mv -v ./zram-generator.conf /usr/lib/systemd/zram-generator.conf.d/1-zram-custom.conf && \
    mv -v ./oomd.conf /usr/lib/systemd/oomd.conf.d/1-oomd-custom.conf
# Ambiente gráfico - gnome-shell e mutter
RUN grep -v '^#' ./rpms-desktop.list | tr '\n' ' ' | xargs dnf install -y --setopt=install_weak_deps=False && \
    dnf config-manager addrepo -y --from-repofile=https://ramonmsilvabr.github.io/gnome-software-plugin-bootc/gnome-software-bootc.repo && \
    dnf install -y --nogpgcheck gnome-software-bootc
# Pacotes essenciais
RUN grep -v '^#' ./rpms-essenciais.list | tr '\n' ' ' | xargs dnf install -y --setopt=install_weak_deps=False && \
    mkdir -p /etc/plymouth && \
    mv -v ./plymouthd.conf /etc/plymouth/plymouthd.conf
WORKDIR /
RUN chmod +x /tmp/workdir/initramfs-regen.sh && \
    bash -c /tmp/workdir/initramfs-regen.sh
# Fase de Limpeza
RUN systemctl mask systemd-remount-fs.service && \
    rm -rvf /tmp/workdir && \
    dnf clean all && \
    rm -rfv /var/cache/* \
        /var/log/* \
        /var/tmp/* \
        /var/lib/dnf/*
# Ajustar container 
RUN bootc container lint