ARG FEDORA_VERSION=44
FROM quay.io/fedora/fedora-bootc:${FEDORA_VERSION} as final
# Cópia da lista de pacotes e de configurações e atribui diretório de trabalho
RUN mkdir /tmp/workdir
WORKDIR /tmp/workdir
COPY /packages/* /configs/* /scripts/* ./* ./
# Módulos, firmware, argumentos de boot e zram
RUN dnf upgrade -y --refresh && \
    grep -v '^#' ./rpms-drivers.list | tr '\n' ' ' | xargs dnf install -y --setopt=install_weak_deps=False&& \
    mv -v ./1-boot-args.toml /usr/lib/bootc/kargs.d/1-boot-args.toml && \
    mv -v ./99-ntsync.conf /usr/lib/modules-load.d/99-ntsync.conf && \
    mv -v ./zram-generator.conf /etc/systemd/
# Ambiente gráfico
RUN dnf install -y gnome-shell --setopt=install_weak_deps=False && \
    grep -v '^#' ./rpms-desktop.list | tr '\n' ' ' | xargs dnf install -y --setopt=install_weak_deps=False && \
    curl -LO https://github.com/ramonmsilvabr/gnome-software-plugin-bootc/releases/download/0.1.3/gnome-software-bootc-0.1.3-1.fc44.x86_64.rpm && \
    dnf install -y ./gnome-software-bootc-0.1.3-1.fc44.x86_64.rpm  
# Pacotes de núcleo
RUN grep -v '^#' ./rpms-essenciais.list | tr '\n' ' ' | xargs dnf install -y --setopt=install_weak_deps=False && \
    mkdir -p /etc/plymouth && \
    mv -v ./plymouthd.conf /etc/plymouth/plymouthd.conf
WORKDIR /
RUN chmod +x /tmp/workdir/initramfs-regen.sh && \
    bash -c /tmp/workdir/initramfs-regen.sh
# Fase de Limpeza
RUN systemctl mask systemd-remount-fs.service && \
    rm -rvf /tmp/workdir && \
    dnf clean all && \
    rm -rfv /var/cache/* \
        /var/lib/* \
        /var/log/* \
        /var/tmp/*
# Ajustar container 
RUN bootc container lint