ARG FEDORA_VERSION=44

# Imagem de compilação de módulos
FROM quay.io/fedora/fedora-bootc:${FEDORA_VERSION} AS builder
RUN dnf upgrade -y 'kernel*' --refresh && \
KERNEL_VERSION="$(rpm -q kernel-core --queryformat '%{VERSION}-%{RELEASE}.%{ARCH}')" && \
dnf install -y 'dnf5-command(config-manager)' && \
dnf install -y fedora-workstation-repositories && \
dnf config-manager setopt rpmfusion-nonfree-nvidia-driver.enabled=1 && \
dnf install -y akmod-nvidia && \
akmods --kernels "$KERNEL_VERSION" --force

# Imagem principal
FROM quay.io/fedora/fedora-bootc:${FEDORA_VERSION} AS final
# Cópia da lista de pacotes e de configurações e atribui diretório de trabalho
RUN mkdir /tmp/workdir
WORKDIR /tmp/workdir
COPY /packages/* /configs/* /scripts/* ./
COPY --from=builder /var/cache/akmods/nvidia/kmod-nvidia*.rpm ./
# Módulos, firmware, drivers de Userspace, módulos e zram
RUN dnf install -y 'dnf5-command(config-manager)' && \
    dnf config-manager addrepo -y --from-repofile=https://nvidia.github.io/libnvidia-container/stable/rpm/nvidia-container-toolkit.repo && \
    dnf install -y fedora-workstation-repositories && \
    dnf config-manager setopt rpmfusion-nonfree-nvidia-driver.enabled=1 && \
    dnf upgrade -y --refresh && \  
    grep -v '^#' ./rpms-drivers.list | tr '\n' ' ' | xargs dnf install -y --setopt=install_weak_deps=False && \
    grep -v '^#' ./rpms-nvidia-containers.list | tr '\n' ' ' | xargs dnf install -y --nogpgcheck --setopt=install_weak_deps=False && \
    dnf install -y ./kmod-nvidia*.rpm \
        xorg-x11-drv-nvidia-cuda libva-nvidia-driver --setopt=install_weak_deps=False && \
    mv -v ./0-nvidia-args.toml /usr/lib/bootc/kargs.d/0-nvidia-args.toml && \
    mv -v ./zram-generator.conf /etc/systemd
ARG SECUREBOOT=true
RUN --mount=type=bind,source=.,target=/context \
/bin/bash -c 'if [ "$SECUREBOOT" = true ]; then \
        mkdir -p ./.actions; \
        cp -r /context/.actions/* ./; \
        bash ./secureboot-sign-modules.sh; \
fi'
# Ambiente gráfico - gnome-shell e mutter
RUN grep -v '^#' ./rpms-desktop.list | tr '\n' ' ' | xargs dnf install -y --setopt=install_weak_deps=False && \
    dnf config-manager addrepo -y --from-repofile=https://ramonmsilvabr.github.io/gnome-software-plugin-bootc/gnome-software-bootc.repo && \
    dnf install -y --nogpgcheck gnome-software-bootc
# Pacotes essenciais
RUN grep -v '^#' ./rpms-essenciais.list | tr '\n' ' ' | xargs dnf install -y --setopt=install_weak_deps=False && \
    mkdir -p /etc/plymouth && \
    mv -v ./plymouthd.conf /etc/plymouth/plymouthd.conf
WORKDIR /
RUN chmod +x /tmp/workdir/initramfs-regen.sh && \
    bash -c /tmp/workdir/initramfs-regen.sh
# Fase de Limpeza
RUN systemctl mask systemd-remount-fs.service && \
    rm -rvf /tmp/workdir && \
    dnf clean all && \
    rm -rfv /var/cache/* \
        /var/log/* \
        /var/tmp/* \
        /var/lib/dnf/
# Ajustar container 
RUN bootc container lint