# Fedora version selection
ARG FEDORA_VERSION=44
# Pull fedora-bootc image as quay.io repo as module build image
FROM quay.io/fedora/fedora-bootc:${FEDORA_VERSION} AS builder
# This handles the proccess of module build
RUN dnf upgrade -y 'kernel*' --refresh && \
KERNEL_VERSION="$(rpm -q kernel-core --queryformat '%{VERSION}-%{RELEASE}.%{ARCH}')" && \
dnf install -y 'dnf5-command(config-manager)' && \
dnf install -y fedora-workstation-repositories && \
dnf config-manager setopt rpmfusion-nonfree-nvidia-driver.enabled=1 && \
dnf install -y akmod-nvidia && \
akmods --kernels "$KERNEL_VERSION" --force

# Pull fedora-bootc from official quay.io repo as final image
FROM quay.io/fedora/fedora-bootc:${FEDORA_VERSION} AS final
# Change working directory
RUN mkdir /tmp/workdir
WORKDIR /tmp/workdir
# Copy all the scripts, built modules rpms configs and package lists
COPY /packages/* /configs/* /scripts/* ./
COPY --from=builder /var/cache/akmods/nvidia/kmod-nvidia*.rpm ./
# Drivers, firmware, hardware support and fine-tuned performance customs
RUN dnf install -y 'dnf5-command(config-manager)' && \
    dnf config-manager addrepo -y --from-repofile=https://nvidia.github.io/libnvidia-container/stable/rpm/nvidia-container-toolkit.repo && \
    dnf install -y fedora-workstation-repositories && \
    dnf config-manager setopt rpmfusion-nonfree-nvidia-driver.enabled=1 && \
    dnf upgrade -y --refresh && \  
    grep -v '^#' ./rpms-drivers.list | tr '\n' ' ' | xargs dnf install -y --setopt=install_weak_deps=False && \
    grep -v '^#' ./rpms-nvidia-containers.list | tr '\n' ' ' | xargs dnf install -y --nogpgcheck --setopt=install_weak_deps=False && \
    dnf install -y ./kmod-nvidia*.rpm \
        xorg-x11-drv-nvidia-cuda libva-nvidia-driver --setopt=install_weak_deps=False && \
    mv -v ./0-nvidia-args.toml /usr/lib/bootc/kargs.d/0-nvidia-args.toml && \
    mkdir -p /usr/lib/systemd/zram-generator.conf.d && \
    mv -v ./zram-generator.conf /usr/lib/systemd/zram-generator.conf.d/1-zram-custom.conf && \
    mv -v ./oomd.conf /usr/lib/systemd/oomd.conf.d/1-oomd-custom.conf
# This handles Secure Boot support gracefully
ARG SECUREBOOT=true
RUN --mount=type=bind,source=.,target=/context \
/bin/bash -c 'if [ "$SECUREBOOT" = true ]; then \
        mkdir -p ./.actions; \
        cp -r /context/.actions/* ./; \
        bash ./secureboot-sign-modules.sh; \
fi'
# Desktop environment and related tools
RUN grep -v '^#' ./rpms-desktop.list | tr '\n' ' ' | xargs dnf install -y --setopt=install_weak_deps=False && \
    dnf config-manager addrepo -y --from-repofile=https://ramonmsilvabr.github.io/gnome-software-plugin-bootc/gnome-software-bootc.repo && \
    dnf install -y --nogpgcheck gnome-software-bootc
# Essential Packages
RUN grep -v '^#' ./rpms-essenciais.list | tr '\n' ' ' | xargs dnf install -y --setopt=install_weak_deps=False && \
    mkdir -p /etc/plymouth && \
    mv -v ./plymouthd.conf /etc/plymouth/plymouthd.conf
# Return to root
WORKDIR /
# This regenerates initramfs for the container
RUN chmod +x /tmp/workdir/initramfs-regen.sh && \
    bash -c /tmp/workdir/initramfs-regen.sh
# Cleanup time
RUN systemctl mask systemd-remount-fs.service && \
    rm -rvf /tmp/workdir && \
    dnf clean all && \
    rm -rfv /var/cache/* \
        /var/log/* \
        /var/tmp/* \
        /var/lib/dnf/
# Ajustar container 
RUN bootc container lint